// analyze-failure.js
// Reads Playwright JSON results, filters failed tests, calls Claude for root cause analysis,
// writes a markdown report to failure-analysis/report.md, and prints a summary to stdout.
// On any Claude API error, logs a warning and exits 0 so CI is not blocked.

'use strict';

const fs = require('fs');
const path = require('path');
const Anthropic = require('@anthropic-ai/sdk');

const RESULTS_FILE = 'test-results/results.json';
const PROMPT_FILE = 'prompts/failure-analysis.md';
const OUTPUT_DIR = 'failure-analysis';
const OUTPUT_FILE = path.join(OUTPUT_DIR, 'report.md');
const CHAR_CAP = 8000;

// Walk the Playwright suite tree and collect all failed specs.
function collectFailures(suite, ancestors = []) {
  const failures = [];
  const title = [...ancestors, suite.title].filter(Boolean).join(' > ');

  for (const spec of suite.specs || []) {
    for (const test of spec.tests || []) {
      for (const result of test.results || []) {
        if (result.status === 'failed' || result.status === 'timedOut') {
          failures.push({ title: title ? `${title} > ${spec.title}` : spec.title, error: result.error });
        }
      }
    }
  }

  for (const child of suite.suites || []) {
    failures.push(...collectFailures(child, title ? [title] : []));
  }

  return failures;
}

function formatFailures(failures) {
  let text = failures
    .map((f) => {
      const msg = f.error?.message || '(no error message)';
      const stack = f.error?.stack ? `\nStack:\n${f.error.stack}` : '';
      return `### ${f.title}\n\nError: ${msg}${stack}`;
    })
    .join('\n\n---\n\n');

  if (text.length > CHAR_CAP) {
    text = text.slice(0, CHAR_CAP) + `\n\n[...truncated at ${CHAR_CAP} characters]`;
  }

  return text;
}

function extractPrompt(markdown) {
  const marker = '## The Prompt';
  const idx = markdown.indexOf(marker);
  if (idx === -1) throw new Error(`"${marker}" heading not found in ${PROMPT_FILE}`);
  const body = markdown.slice(idx + marker.length);
  const nextSection = body.search(/\n## /);
  return (nextSection === -1 ? body : body.slice(0, nextSection)).trim();
}

async function main() {
  // Read results
  if (!fs.existsSync(RESULTS_FILE)) {
    console.warn(`analyze-failure: ${RESULTS_FILE} not found -- skipping analysis`);
    process.exit(0);
  }

  let results;
  try {
    results = JSON.parse(fs.readFileSync(RESULTS_FILE, 'utf8'));
  } catch (err) {
    console.warn(`analyze-failure: failed to parse ${RESULTS_FILE}: ${err.message}`);
    process.exit(0);
  }

  // DEBUG: log top-level suite structure
  console.log(`[DEBUG] suites count: ${(results.suites || []).length}`);
  (results.suites || []).forEach((s, i) => {
    console.log(`[DEBUG] suite[${i}].title=${JSON.stringify(s.title)} specs=${(s.specs||[]).length} suites=${(s.suites||[]).length}`);
  });

  const failures = (results.suites || []).flatMap((s) => collectFailures(s));

  console.log(`[DEBUG] failures found: ${failures.length}`);
  if (failures.length > 0) {
    console.log(`[DEBUG] first failure title: ${failures[0].title}`);
    console.log(`[DEBUG] first failure error: ${JSON.stringify(failures[0].error)}`);
  }

  if (failures.length === 0) {
    console.log('analyze-failure: no failures found -- skipping analysis');
    process.exit(0);
  }

  const failureText = formatFailures(failures);
  console.log(`[DEBUG] failureText length: ${failureText.length}`);
  console.log(`[DEBUG] failureText preview: ${failureText.slice(0, 200)}`);

  // Build prompt
  let promptTemplate;
  try {
    promptTemplate = extractPrompt(fs.readFileSync(PROMPT_FILE, 'utf8'));
  } catch (err) {
    console.warn(`analyze-failure: failed to read prompt: ${err.message}`);
    process.exit(0);
  }
  console.log(`[DEBUG] prompt contains placeholder: ${promptTemplate.includes('{FAILURE_OUTPUT}')}`);

  const prompt = promptTemplate.replace('{FAILURE_OUTPUT}', failureText);

  // Call Claude
  let report;
  try {
    const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
    const response = await client.messages.create({
      model: 'claude-opus-4-6',
      max_tokens: 1024,
      messages: [{ role: 'user', content: prompt }],
    });
    report = response.content.find((b) => b.type === 'text')?.text ?? '(empty response)';
  } catch (err) {
    console.warn(`analyze-failure: Claude API call failed -- ${err.message}`);
    process.exit(0);
  }

  // Write report
  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  const header = `# Test Failure Analysis\n\n_Generated by Claude on ${new Date().toISOString()}_\n\n---\n\n`;
  fs.writeFileSync(OUTPUT_FILE, header + report, 'utf8');

  // Print summary to CI logs
  const summary = report.replace(/\n+/g, ' ').trim().slice(0, 200);
  console.log(`\nAI Analysis: ${summary}${report.length > 200 ? '...' : ''}\n`);
  console.log(`Full report written to ${OUTPUT_FILE}`);
}

main();
